import { Injectable } from '@angular/core';

import 'rxjs/add/operator/map';

/*
  Generated class for the DevProvider provider.

  See https://angular.io/docs/ts/latest/guide/dependency-injection.html
  for more info on providers and Angular DI.
*/
@Injectable()
export class DevProvider {

  constructor() {
    console.log('Hello DevProvider Provider');
  }
  private _devKeys = [
    "CAROUSEL0.IMG_URL",
    "CAROUSEL1.IMG_URL",
    "CAROUSEL1.HTML_TITTLES.0.IMG_URL",
    "CAROUSEL1.HTML_TITTLES.1.IMG_URL",
    "CAROUSEL1.HTML_TITTLES.2.IMG_URL",
    "CAROUSEL1.HTML_TITTLES.3.IMG_URL",
    "CAROUSEL1.HTML_TITTLES.4.IMG_URL",
    "CAROUSEL1.HTML_TITTLES.5.IMG_URL",
    "CAROUSEL2.IMG_URL",
    "CAROUSEL3.IMG_URL",
    "CAROUSEL4.IMG_URL",
    "CAROUSEL4.HTML_TITTLES.LOGO_URL",
    "CAROUSEL4.HTML_TITTLES.SIGN_URL",
    "CARD0.IMG_URL",
    "CARD0.CARD_IMG_URL",
    "CARD0.DETAILS.INFO.0.IMG_URL",
    "CARD0.DETAILS.INFO.1.IMG_URL",
    "CARD0.DETAILS.INFO.2.IMG_URL",
    "CARD0.DETAILS.INFO.3.IMG_URL",
    "CARD0.DETAILS.INFO.4.IMG_URL",
    "CARD0.DETAILS.INFO.5.IMG_URL",
    "CARD0.DETAILS.INFO.6.IMG_URL",
    "CARD0.DETAILS.VIDEO.0.ID",
    "CARD0.DETAILS.VIDEO.0.IMG_URL",
    "CARD0.DETAILS.VIDEO.1.ID",
    "CARD0.DETAILS.VIDEO.1.IMG_URL",
    "CARD0.DETAILS.VIDEO.2.ID",
    "CARD0.DETAILS.VIDEO.2.IMG_URL",
    "CARD0.DETAILS.VIDEO.3.ID",
    "CARD0.DETAILS.VIDEO.3.IMG_URL",
    "CARD0.DETAILS.VIDEO.4.ID",
    "CARD0.DETAILS.VIDEO.4.IMG_URL",
    "CARD0.DETAILS.VIDEO.5.ID",
    "CARD0.DETAILS.VIDEO.5.IMG_URL",
    "CARD0.DETAILS.VIDEO.6.ID",
    "CARD0.DETAILS.VIDEO.6.IMG_URL",
    "CARD0.DETAILS.VIDEO.7.ID",
    "CARD0.DETAILS.VIDEO.7.IMG_URL",
    "CARD1.IMG_URL",
    "CARD1.CARD_IMG_URL",
    "CARD1.DETAILS.INFO.0.IMG_URL",
    "CARD1.DETAILS.INFO.1.IMG_URL",
    "CARD1.DETAILS.INFO.2.IMG_URL",
    "CARD1.DETAILS.INFO.3.IMG_URL",
    "CARD1.DETAILS.INFO.4.IMG_URL",
    "CARD1.DETAILS.INFO.5.IMG_URL",
    "CARD1.DETAILS.INFO.6.IMG_URL",
    "CARD1.DETAILS.INFO.7.IMG_URL",
    "CARD1.DETAILS.INFO.8.IMG_URL",
    "CARD2.IMG_URL",
    "CARD2.CARD_IMG_URL",
    "CARD2.DETAILS.INFO.0.IMG_URL",
    "CARD2.DETAILS.INFO.1.IMG_URL",
    "CARD2.DETAILS.INFO.2.IMG_URL",
    "CARD2.DETAILS.INFO.3.IMG_URL",
    "CARD2.DETAILS.INFO.4.IMG_URL",
    "CARD2.DETAILS.INFO.5.IMG_URL",
    "CARD2.DETAILS.INFO.6.IMG_URL",
    "CARD2.DETAILS.INFO.7.IMG_URL",
    "CARD3.IMG_URL",
    "CARD3.CARD_IMG_URL",
    "CARD3.DETAILS.INFO.0.IMG_URL",
    "CARD3.DETAILS.INFO.1.IMG_URL",
    "CARD3.DETAILS.INFO.2.IMG_URL",
    "CARD3.DETAILS.INFO.3.IMG_URL",
    "CARD3.DETAILS.INFO.4.IMG_URL",
    "CARD3.DETAILS.INFO.5.IMG_URL",
    "CARD3.DETAILS.INFO.6.IMG_URL",
    "CARD3.DETAILS.INFO.7.IMG_URL",
    "CARD3.DETAILS.INFO.8.IMG_URL",
    "CARD3.DETAILS.INFO.9.IMG_URL",
    "CARD3.DETAILS.INFO.10.IMG_URL",
    "CARD3.DETAILS.INFO.11.IMG_URL",
    "CARD3.DETAILS.INFO.12.IMG_URL",
    "CARD3.DETAILS.INFO.13.IMG_URL",
    "CARD4.IMG_URL",
    "CARD4.CARD_IMG_URL",
    "CARD4.DETAILS.INFO.0.IMG_URL",
    "CARD4.DETAILS.INFO.1.IMG_URL",
    "CARD4.DETAILS.INFO.2.IMG_URL",
    "CARD4.DETAILS.INFO.3.IMG_URL",
    "CARD4.DETAILS.INFO.4.IMG_URL",
    "CARD4.DETAILS.INFO.5.IMG_URL",
    "CARD4.DETAILS.INFO.6.IMG_URL",
    "CARD4.DETAILS.INFO.7.IMG_URL",
    "CARD4.DETAILS.INFO.8.IMG_URL",
    "CARD5.IMG_URL",
    "CARD5.CARD_IMG_URL",
    "CARD5.DETAILS.INFO.0.IMG_URL",
    "CARD5.DETAILS.INFO.1.IMG_URL",
    "CARD5.DETAILS.INFO.2.IMG_URL",
    "CARD5.DETAILS.INFO.3.IMG_URL",
    "CARD5.DETAILS.INFO.4.IMG_URL",
    "CARD5.DETAILS.INFO.5.IMG_URL",
    "CARD5.DETAILS.INFO.6.IMG_URL",
    "CARD5.DETAILS.INFO.7.IMG_URL",
    "CARD5.DETAILS.INFO.8.IMG_URL",
    "CARD5.DETAILS.INFO.9.IMG_URL",
    "CARD5.DETAILS.INFO.10.IMG_URL",
    "CARD5.DETAILS.INFO.11.IMG_URL",
    "CARD5.DETAILS.INFO.12.IMG_URL",
    "CARD5.DETAILS.INFO.13.IMG_URL",
    "CARD5.DETAILS.INFO.14.IMG_URL"
  ]
  private _devValues = [
    "assets/img/carousel1.png",
    "assets/img/carousel2.png",
    "assets/img/eye_icon.png",
    "assets/img/prompts_icon.png",
    "assets/img/email_icon.png",
    "assets/img/people_icon.png",
    "assets/img/funds_icon.png",
    "assets/img/page_icon.png",
    "assets/img/carousel3.png",
    "assets/img/carousel4.png",
    "assets/img/carousel5.png",
    "assets/img/pfizerLogo.png",
    "assets/img/pfizerSignature.png",
    "assets/img/explore/product_integrity_bg_img.png",
    "assets/img/ExploreModel/product_integrity_card_bg.png",
    "assets/img/ExploreModel/Product Integrity Photos-Cards/Counterfeit Tablets China (card 1).png",
    "assets/img/ExploreModel/Product Integrity Photos-Cards/Counterfeit Packaging (card 2).png",
    "assets/img/ExploreModel/Product Integrity Photos-Cards/Unsanitary Manufacture Conditions (card 3).png",
    "assets/img/ExploreModel/Product Integrity Photos-Cards/Counterfeit Printing Machine (card 4).png",
    "assets/img/ExploreModel/Product Integrity Photos-Cards/Counterfeit Injectables (card 5).png",
    "assets/img/ExploreModel/Product Integrity Photos-Cards/Unregulated Manufacturing (card 6).png",
    "assets/img/ExploreModel/Product Integrity Photos-Cards/Police Raid Counterfeit Manufacturing (card 7).png",
    "5498212614001",
    "assets/img/ExploreModel/generic_video_card.png",
    "5498209170001",
    "assets/img/ExploreModel/generic_video_card.png",
    "5498212603001",
    "assets/img/ExploreModel/generic_video_card.png",
    "5498212607001",
    "assets/img/ExploreModel/generic_video_card.png",
    "5498209178001",
    "assets/img/ExploreModel/generic_video_card.png",
    "5498219017001",
    "assets/img/ExploreModel/generic_video_card.png",
    "5498199888001",
    "assets/img/ExploreModel/generic_video_card.png",
    "5498219024001",
    "assets/img/ExploreModel/generic_video_card.png",
    "assets/img/explore/information_incident_bg_img.png",
    "assets/img/ExploreModel/information_incident_card_bg.png",
    "assets/img/ExploreModel/Information Incident Reporting Photos-Cards/Information Incident Reporting Card 1.png",
    "assets/img/ExploreModel/Information Incident Reporting Photos-Cards/You are the key card 3.png",
    "assets/img/ExploreModel/Information Incident Reporting Photos-Cards/Lost device card 4.png",
    "assets/img/ExploreModel/Information Incident Reporting Photos-Cards/Ask Questions card 5.png",
    "assets/img/ExploreModel/Information Incident Reporting Photos-Cards/Personal Information Card 6.png",
    "assets/img/ExploreModel/Information Incident Reporting Photos-Cards/Sensitive Pers Info Card7.png",
    "assets/img/ExploreModel/Information Incident Reporting Photos-Cards/PFE proprietary Info card 8.png",
    "assets/img/ExploreModel/Information Incident Reporting Photos-Cards/Intellectual Property Card 9.png",
    "assets/img/ExploreModel/Information Incident Reporting Photos-Cards/Misuse of Information Card 10.png",
    "assets/img/explore/personal_security_bg_img.png",
    "assets/img/ExploreModel/personal_security_card_bg.png",
    "assets/img/ExploreModel/Personal Security Photos-Cards/Aggressive Behavior Prohibited (card1).png",
    "assets/img/ExploreModel/Personal Security Photos-Cards/jez-timms-157470 (card2).png",
    "assets/img/ExploreModel/Personal Security Photos-Cards/clem-onojeghuo-189252(card3).png",
    "assets/img/ExploreModel/Personal Security Photos-Cards/matt-popovich-60437(card4).png",
    "assets/img/ExploreModel/Personal Security Photos-Cards/Emergency Contact List (card 5).png",
    "assets/img/ExploreModel/Personal Security Photos-Cards/Social Media - Danger Zone (card 6).png",
    "assets/img/ExploreModel/Personal Security Photos-Cards/brian-gaid-177004(card7).png",
    "assets/img/ExploreModel/Personal Security Photos-Cards/Take Action (card 8).png",
    "assets/img/explore/travel_security_bg_img.png",
    "assets/img/ExploreModel/travel_security_card_bg.png",
    "assets/img/ExploreModel/Travel Security Photos-Cards/GSOC(card 1).png",
    "assets/img/ExploreModel/Travel Security Photos-Cards/Travel Help (card 2).png",
    "assets/img/ExploreModel/Travel Security Photos-Cards/Medical Emergency (card 3).png",
    "assets/img/ExploreModel/Travel Security Photos-Cards/jose-martin-651 9card4.png",
    "assets/img/ExploreModel/Travel Security Photos-Cards/hannes-wolf(card 5).png",
    "assets/img/ExploreModel/Travel Security Photos-Cards/Emergency Contact List (card 6).png",
    "assets/img/ExploreModel/Travel Security Photos-Cards/thorn-yang-104864 (card 7).png",
    "assets/img/ExploreModel/Travel Security Photos-Cards/nabeel-syed-2856 (card 8).png",
    "assets/img/ExploreModel/Travel Security Photos-Cards/credit-card (card 9).png",
    "assets/img/ExploreModel/Travel Security Photos-Cards/Plan Your Travel (card 10).png",
    "assets/img/ExploreModel/Travel Security Photos-Cards/Pfizer Travel Desk (card 11).png",
    "assets/img/ExploreModel/Travel Security Photos-Cards/Hazardous Country Travel Program (card12).png",
    "assets/img/ExploreModel/Travel Security Photos-Cards/Safe Passage (card 13).png",
    "assets/img/ExploreModel/Travel Security Photos-Cards/GSOC(card 14).png",
    "assets/img/explore/crisis_management_bg_img.png",
    "assets/img/ExploreModel/crisis_management_card_bg.png",
    "assets/img/ExploreModel/CrisisManagementPhotos-Cards/Crisiscard1.png",
    "assets/img/ExploreModel/CrisisManagementPhotos-Cards/Crisiscard2.png",
    "assets/img/ExploreModel/CrisisManagementPhotos-Cards/Crisiscard3.png",
    "assets/img/ExploreModel/CrisisManagementPhotos-Cards/Crisiscard4.png",
    "assets/img/ExploreModel/CrisisManagementPhotos-Cards/Crisiscard5.png",
    "assets/img/ExploreModel/CrisisManagementPhotos-Cards/Crisiscard6.png",
    "assets/img/ExploreModel/CrisisManagementPhotos-Cards/Crisiscard7.png",
    "assets/img/ExploreModel/CrisisManagementPhotos-Cards/Crisiscard8.png",
    "assets/img/ExploreModel/CrisisManagementPhotos-Cards/Crisiscard9.png",
    "assets/img/explore/information_protection_bg_img.png",
    "assets/img/ExploreModel/information_protection_card_bg.png",
    "assets/img/ExploreModel/Information Protection Photos-Cards/rawpixel-com-267079(card 1).png",
    "assets/img/ExploreModel/Information Protection Photos-Cards/helloquence-61189(card 2).png",
    "assets/img/ExploreModel/Information Protection Photos-Cards/andrew-neel-218073(card 3).png",
    "assets/img/ExploreModel/Information Protection Photos-Cards/raffik-lopes-56931.(card 4)jpg.png",
    "assets/img/ExploreModel/Information Protection Photos-Cards/andrew-neel-218073(card 5).png",
    "assets/img/ExploreModel/Information Protection Photos-Cards/nick-turner-2570(card 6).png",
    "assets/img/ExploreModel/Information Protection Photos-Cards/rawpixel-com-267082(card 7).png",
    "assets/img/ExploreModel/Information Protection Photos-Cards/taduuda-72915(card 8).png",
    "assets/img/ExploreModel/Information Protection Photos-Cards/boriskin-vladislav-19014(card 9).png",
    "assets/img/ExploreModel/Information Protection Photos-Cards/stanley-dai-242205(Card 10).png",
    "assets/img/ExploreModel/Information Protection Photos-Cards/gilles-lambert-8649.(Card 11).png",
    "assets/img/ExploreModel/Information Protection Photos-Cards/daria-nepriakhina-99254(Card 12).png",
    "assets/img/ExploreModel/Information Protection Photos-Cards/glenn-carstens-peters-203007(Card 13).png",
    "assets/img/ExploreModel/Information Protection Photos-Cards/rawpixel-com-250087(Card 14).png",
    "assets/img/ExploreModel/Information Protection Photos-Cards/courtneyrecker(Card15).png"
  ]

  getDevData(){
    let data = [];
    data = this._devKeys.map((d,i)=>{
      let r:any = {};
      r.key = d;
      r.value = this._devValues[i];
      return r;
    })
    return data;
  }


}
